project_id = "uoskbpqmlvgrwoqosnew"

[functions.search-availability]
verify_jwt = false

[functions.confirm-appointment]
verify_jwt = false

[functions.notify-call-started]
verify_jwt = false

[functions.notify-call-ended]
verify_jwt = false

[functions.send-confirmation-sms]
verify_jwt = false