project_id = "uoskbpqmlvgrwoqosnew"

[functions.search-availability]
verify_jwt = false

[functions.confirm-appointment]
verify_jwt = false

[functions.notify-call-started]
verify_jwt = false

[functions.notify-call-ended]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.lookup-package]
verify_jwt = false

[functions.get-delivery-options]
verify_jwt = false

[functions.confirm-delivery-change]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.calculate-delivery]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.explain-charges]
verify_jwt = false

[functions.get-billing-details]
verify_jwt = false

[functions.get-customer-info]
verify_jwt = false

[functions.get-promotions]
verify_jwt = false

[functions.escalate-to-agent]
verify_jwt = false

[functions.process-incident-routing]
verify_jwt = false

[functions.validate-pizza-order]
verify_jwt = false

[functions.calculate-pizza-pricing]
verify_jwt = false