project_id = "uoskbpqmlvgrwoqosnew"

[functions.search-availability]
verify_jwt = false

[functions.confirm-appointment]
verify_jwt = false

[functions.notify-call-started]
verify_jwt = false

[functions.notify-call-ended]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.lookup-package]
verify_jwt = false

[functions.get-delivery-options]
verify_jwt = false

[functions.confirm-delivery-change]
verify_jwt = false

[functions.send-delivery-sms]
verify_jwt = false